### ISSUE TITLE
REDACTED

### ISSUE THREAD

**Issue by sidstory** [Pixel-Props/build.prop#9]
You are so awesome. LSPosed is so bad please make better alternative.

**Comment by likkai** [comment]
Simple, because @0x11DFE is incompetent and unable to maintain it. He only knows how to make a prop (which everyone can make) and call himself a developer for self satisfactory

**Comment by likkai** [comment]
Cuz Tesla is incompetent enough to maintain lsposed, he can only made these props (which anyone can do it) and call himself a developer for self satisfactory. See? He even deleted my comment, yet he is still throwing a tantrum on telegram by yelling lsposed hide something and is not open source. 🤡🤡🤡
